-- AlgoVision Postgres schema — Phase 1 subset of spec §5.1
-- MongoDB-shaped tables (visualization_sessions frames, notepad content) are NOT here;
-- those live in Mongo per §5.3 and are out of scope until Phase 3/5.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE users (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name          varchar(255) NOT NULL,
    email         varchar(255) UNIQUE NOT NULL,
    password_hash varchar(255) NOT NULL,
    streak        int NOT NULL DEFAULT 0,
    rating        int NOT NULL DEFAULT 0,
    preferences   jsonb NOT NULL DEFAULT '{}',
    created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TYPE difficulty_enum AS ENUM ('easy', 'medium', 'hard');
CREATE TYPE visualization_tier_enum AS ENUM ('core', 'extended', 'conceptual');

CREATE TABLE problems (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    title               varchar(255) NOT NULL,
    difficulty          difficulty_enum NOT NULL,
    pattern             varchar(100) NOT NULL,
    statement           text NOT NULL,
    constraints         text,
    examples            jsonb NOT NULL DEFAULT '[]',
    testcases           jsonb NOT NULL DEFAULT '[]',
    tags                text[] NOT NULL DEFAULT '{}',
    source              varchar(50) NOT NULL DEFAULT 'custom',
    visualization_tier  visualization_tier_enum NOT NULL DEFAULT 'core',
    visualization_meta  jsonb NOT NULL DEFAULT '{}',
    license             varchar(50) NOT NULL DEFAULT 'original',
    attribution_text    varchar(255),
    function_name       varchar(100),
    starter_code        text,
    hints               text[] NOT NULL DEFAULT '{}',
    follow_up           text,
    harness_type        varchar(20) NOT NULL DEFAULT 'stdio',  -- 'function' | 'stdio' | 'operations'
    created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TYPE solution_status_enum AS ENUM ('accepted', 'wrong_answer', 'tle', 'mle', 'runtime_error');

CREATE TABLE solutions (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid NOT NULL REFERENCES users(id),
    problem_id    uuid NOT NULL REFERENCES problems(id),
    language      varchar(50) NOT NULL,
    code          text NOT NULL,
    runtime_ms    int,
    memory_kb     int,
    status        solution_status_enum,
    created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE learning_progress (
    user_id       uuid NOT NULL REFERENCES users(id),
    pattern       varchar(100) NOT NULL,
    mastery_score float NOT NULL DEFAULT 0,
    attempts      int NOT NULL DEFAULT 0,
    accuracy      float NOT NULL DEFAULT 0,
    avg_speed_ms  int NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, pattern)
);

CREATE TYPE notepad_content_type_enum AS ENUM ('sketch', 'text');

CREATE TABLE notepads (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid NOT NULL REFERENCES users(id),
    problem_id    uuid REFERENCES problems(id),   -- null = global scratchpad (spec §5.1)
    content_type  notepad_content_type_enum NOT NULL DEFAULT 'text',
    content       jsonb NOT NULL DEFAULT '{}',
    updated_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, problem_id, content_type)
);

-- streak bookkeeping: last day (UTC) an accepted submission landed
ALTER TABLE users ADD COLUMN last_accepted_date date;

CREATE INDEX idx_solutions_user_id ON solutions(user_id);
CREATE INDEX idx_solutions_problem_id ON solutions(problem_id);
CREATE INDEX idx_problems_pattern ON problems(pattern);
CREATE INDEX idx_problems_tier ON problems(visualization_tier);

-- Seed sample Tier 1 problems for the Phase 1 catalog. Two harnesses coexist:
-- function-signature (LeetCode-style — function_name/starter_code set, testcases
-- are {args, expected}) and stdin/stdout (function_name null, testcases are
-- {input, output}) — see judge-service and spec §6.6a.
INSERT INTO problems (title, difficulty, pattern, statement, constraints, examples, testcases, tags, source, visualization_tier, visualization_meta, function_name, starter_code, hints, follow_up) VALUES
('Two Sum', 'easy', 'hashing',
 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.',
 E'- 2 <= nums.length <= 10^4\n- -10^9 <= nums[i] <= 10^9\n- -10^9 <= target <= 10^9\n- Only one valid answer exists.',
 '[{"input": "nums = [2,7,11,15], target = 9", "output": "[0,1]", "explanation": "Because nums[0] + nums[1] == 9, we return [0, 1]."}, {"input": "nums = [3,2,4], target = 6", "output": "[1,2]", "explanation": null}, {"input": "nums = [3,3], target = 6", "output": "[0,1]", "explanation": null}]',
 '[{"args": [[2,7,11,15], 9], "expected": [0,1]}, {"args": [[3,2,4], 6], "expected": [1,2]}, {"args": [[3,3], 6], "expected": [0,1]}, {"args": [[2,5,5,11], 10], "expected": [1,2]}, {"args": [[0,4,3,0], 0], "expected": [0,3]}, {"args": [[-3,4,3,90], 0], "expected": [0,2]}, {"args": [[-1,-2,-3,-4,-5], -8], "expected": [2,4]}]',
 ARRAY['array','hashing'], 'custom', 'core', '{"array": true, "hashmap": true}',
 'twoSum', E'def twoSum(nums, target):\n    pass\n',
 ARRAY[
   'A really brute force way would be to search for all possible pairs of numbers, but that would be too slow.',
   'So, if we fix one of the numbers, say x, we have to scan the entire array to find the next number y = target - x. Can we change our array somehow so that this search becomes faster?',
   'Without changing the array, can we use additional space to speed up the search? A hash map lets you check whether the complement of the current number exists in O(1).'
 ],
 'Can you come up with an algorithm that is less than O(n^2) time complexity?'),
('Valid Parentheses', 'easy', 'stack',
 'Given a string s containing just the characters ()[]{}, determine if the input string is valid.',
 E'- 1 <= s.length <= 10^4\n- s consists of parentheses only ()[]{}.',
 '[{"input": "s = \"()\"", "output": "true", "explanation": null}, {"input": "s = \"()[]{}\"", "output": "true", "explanation": null}, {"input": "s = \"(]\"", "output": "false", "explanation": null}, {"input": "s = \"([)]\"", "output": "false", "explanation": "The brackets close in the wrong order — the ( opened before [ must also close after it."}]',
 '[{"args": ["()[]{}"], "expected": true}, {"args": ["(]"], "expected": false}, {"args": ["([)]"], "expected": false}, {"args": ["{[]}"], "expected": true}, {"args": ["((()))"], "expected": true}, {"args": ["]"], "expected": false}, {"args": ["([{}])"], "expected": true}, {"args": ["((("], "expected": false}]',
 ARRAY['stack','string'], 'custom', 'core', '{"stack": true}',
 'isValid', E'def isValid(s):\n    pass\n',
 ARRAY[
   'Use a stack of characters.',
   'When you encounter an opening bracket, push it onto the stack.',
   'When you encounter a closing bracket, check whether the top of the stack is the matching opening bracket. If it is, pop it; otherwise the string is invalid.'
 ], NULL),
('Reverse Linked List', 'easy', 'linked_list',
 'Given the head of a singly linked list, reverse the list, and return the reversed list. For judging, the list is passed as a Python list of values; return the reversed list of values.',
 E'- The number of nodes in the list is the range [0, 5000].\n- -5000 <= Node.val <= 5000',
 '[{"input": "head = [1,2,3,4,5]", "output": "[5,4,3,2,1]", "explanation": null}, {"input": "head = [1,2]", "output": "[2,1]", "explanation": null}, {"input": "head = []", "output": "[]", "explanation": null}]',
 '[{"args": [[1,2,3,4,5]], "expected": [5,4,3,2,1]}, {"args": [[1,2]], "expected": [2,1]}, {"args": [[]], "expected": []}, {"args": [[1]], "expected": [1]}, {"args": [[1,2,3]], "expected": [3,2,1]}, {"args": [[10,20,30,40,50,60]], "expected": [60,50,40,30,20,10]}, {"args": [[-1,-2,-3]], "expected": [-3,-2,-1]}]',
 ARRAY['linked_list'], 'custom', 'core', '{"linked_list": true}',
 'reverseList', E'def reverseList(values):\n    pass\n',
 '{}', 'A linked list can be reversed either iteratively or recursively. Could you implement both?'),
('Binary Tree Level Order Traversal', 'medium', 'trees',
 'Given the root of a binary tree, return the level order traversal of its nodes'' values. For judging, the tree is passed as a level-order list with None for missing nodes; return the list of levels.',
 E'- The number of nodes in the tree is in the range [0, 2000].\n- -1000 <= Node.val <= 1000',
 '[{"input": "root = [3,9,20,null,null,15,7]", "output": "[[3],[9,20],[15,7]]", "explanation": null}, {"input": "root = [1]", "output": "[[1]]", "explanation": null}, {"input": "root = []", "output": "[]", "explanation": null}]',
 '[{"args": [[3,9,20,null,null,15,7]], "expected": [[3],[9,20],[15,7]]}, {"args": [[1]], "expected": [[1]]}, {"args": [[]], "expected": []}, {"args": [[1,2,3,4,5,6,7]], "expected": [[1],[2,3],[4,5,6,7]]}, {"args": [[5,3,8,null,4,7,9]], "expected": [[5],[3,8],[4,7,9]]}, {"args": [[1,2]], "expected": [[1],[2]]}]',
 ARRAY['tree','bfs'], 'custom', 'core', '{"tree": true}',
 'levelOrder', E'def levelOrder(values):\n    pass\n', '{}', NULL),
('Climbing Stairs', 'easy', 'dp',
 'You are climbing a staircase. It takes n steps to reach the top. Each time you can climb 1 or 2 steps. In how many distinct ways can you climb to the top? Read n from stdin, print the answer.',
 E'- 1 <= n <= 45',
 '[{"input": "n = 2", "output": "2", "explanation": "There are two ways to climb to the top: 1 step + 1 step, or 2 steps."}, {"input": "n = 3", "output": "3", "explanation": "There are three ways to climb to the top: 1+1+1, 1+2, or 2+1."}]',
 '[{"input": "3\n", "output": "3\n"}, {"input": "4\n", "output": "5\n"}, {"input": "1\n", "output": "1\n"}, {"input": "5\n", "output": "8\n"}, {"input": "6\n", "output": "13\n"}, {"input": "10\n", "output": "89\n"}, {"input": "45\n", "output": "1836311903\n"}]',
 ARRAY['dp'], 'custom', 'core', '{"dp_1d": true}', NULL, NULL,
 ARRAY[
   'To reach step n, you must have come from step n-1 (then take 1 step) or step n-2 (then take 2 steps).',
   'That means the number of ways to reach step n is the sum of the ways to reach n-1 and n-2 — this is the Fibonacci recurrence.'
 ], NULL),
('A Plus B', 'easy', 'math',
 'Read two space-separated integers a and b from stdin, print their sum.',
 E'- -10^9 <= a, b <= 10^9',
 '[{"input": "1 2", "output": "3", "explanation": null}, {"input": "5 7", "output": "12", "explanation": null}, {"input": "-3 3", "output": "0", "explanation": null}]',
 '[{"input": "1 2\n", "output": "3\n"}, {"input": "5 7\n", "output": "12\n"}, {"input": "-3 3\n", "output": "0\n"}, {"input": "100 200\n", "output": "300\n"}, {"input": "-1000000000 1000000000\n", "output": "0\n"}, {"input": "999999999 1\n", "output": "1000000000\n"}, {"input": "0 0\n", "output": "0\n"}]',
 ARRAY['math'], 'custom', 'core', '{}', NULL, NULL, '{}', NULL);

-- Blind 75 batch 1 (15 problems) — see spec §6.6a: 'Blind 75' is a long-public
-- community list (not one company's paid curated product like NeetCode 150/250
-- would be), so it's catalogued here. Statements are original wording, not
-- reproduced from LeetCode. All 15 reference solutions verified via a real
-- /submissions call before being committed.
INSERT INTO problems (title, difficulty, pattern, statement, constraints, examples, testcases, tags, source, visualization_tier, visualization_meta, function_name, starter_code, hints, follow_up) VALUES

('Best Time to Buy and Sell Stock', 'easy', 'array',
 'You are given a list of daily stock prices, where the value at each position is the price on that day. You may complete at most one transaction: buy on one day and sell on a later day. Return the maximum profit you can achieve. If no profit is possible, return 0.',
 E'- 1 <= prices.length <= 10^5\n- 0 <= prices[i] <= 10^4',
 '[{"input": "prices = [7,1,5,3,6,4]", "output": "5", "explanation": "Buy on day 2 (price 1) and sell on day 5 (price 6), profit = 6 - 1 = 5."}, {"input": "prices = [7,6,4,3,1]", "output": "0", "explanation": "Prices only fall, so no transaction is profitable."}]',
 '[{"args": [[7,1,5,3,6,4]], "expected": 5}, {"args": [[7,6,4,3,1]], "expected": 0}, {"args": [[1,2]], "expected": 1}]',
 ARRAY['array','blind75'], 'blind75', 'core', '{"array": true}',
 'maxProfit', E'def maxProfit(prices):\n    pass\n',
 ARRAY['Track the lowest price seen so far as you scan left to right.', 'At each day, the best profit if you sold today is today''s price minus the lowest price seen before it.'],
 NULL),

('Contains Duplicate', 'easy', 'hashing',
 'Given a list of integers, return true if any value appears at least twice, and false if every element is distinct.',
 E'- 1 <= nums.length <= 10^5\n- -10^9 <= nums[i] <= 10^9',
 '[{"input": "nums = [1,2,3,1]", "output": "true", "explanation": "1 appears twice."}, {"input": "nums = [1,2,3,4]", "output": "false", "explanation": null}]',
 '[{"args": [[1,2,3,1]], "expected": true}, {"args": [[1,2,3,4]], "expected": false}, {"args": [[1,1,1,3,3,4,3,2,4,2]], "expected": true}]',
 ARRAY['hashing','blind75'], 'blind75', 'core', '{"hashmap": true}',
 'hasDuplicate', E'def hasDuplicate(nums):\n    pass\n',
 ARRAY['A set only keeps unique values — compare its size to the original list''s length.'],
 NULL),

('Product of Array Except Self', 'medium', 'array',
 'Given a list of integers nums, return a new list where each element at index i is the product of all elements in nums except nums[i]. You must do this without using division, and ideally in O(n) time.',
 E'- 2 <= nums.length <= 10^5\n- -30 <= nums[i] <= 30\n- The product of any prefix or suffix fits in a 32-bit integer.',
 '[{"input": "nums = [1,2,3,4]", "output": "[24,12,8,6]", "explanation": null}, {"input": "nums = [-1,1,0,-3,3]", "output": "[0,0,9,0,0]", "explanation": null}]',
 '[{"args": [[1,2,3,4]], "expected": [24,12,8,6]}, {"args": [[-1,1,0,-3,3]], "expected": [0,0,9,0,0]}, {"args": [[2,3]], "expected": [3,2]}]',
 ARRAY['array','blind75'], 'blind75', 'core', '{"array": true}',
 'productExceptSelf', E'def productExceptSelf(nums):\n    pass\n',
 ARRAY['For each index, the answer is (product of everything to its left) times (product of everything to its right).', 'Compute a running prefix-product array left to right, then fold in a running suffix-product right to left.'],
 'Can you solve it in O(n) time without using the division operation, using only the output array as extra space (not counting it)?'),

('Maximum Subarray', 'medium', 'array',
 'Given a list of integers, find the contiguous subarray (containing at least one number) with the largest sum, and return that sum.',
 E'- 1 <= nums.length <= 10^5\n- -10^4 <= nums[i] <= 10^4',
 '[{"input": "nums = [-2,1,-3,4,-1,2,1,-5,4]", "output": "6", "explanation": "The subarray [4,-1,2,1] has the largest sum, 6."}, {"input": "nums = [1]", "output": "1", "explanation": null}]',
 '[{"args": [[-2,1,-3,4,-1,2,1,-5,4]], "expected": 6}, {"args": [[1]], "expected": 1}, {"args": [[5,4,-1,7,8]], "expected": 23}]',
 ARRAY['array','blind75'], 'blind75', 'core', '{"array": true}',
 'maxSubArray', E'def maxSubArray(nums):\n    pass\n',
 ARRAY['At each position, decide whether extending the previous subarray is better than starting a new one here (Kadane''s algorithm).'],
 NULL),

('3Sum', 'medium', 'two_pointer',
 'Given a list of integers, return all unique triplets [a, b, c] such that a + b + c = 0. Each triplet''s three values must be in ascending order, and the returned list of triplets must itself be sorted in ascending order with no duplicate triplets (this fixed ordering makes the expected output unique for judging).',
 E'- 3 <= nums.length <= 3000\n- -10^5 <= nums[i] <= 10^5',
 '[{"input": "nums = [-1,0,1,2,-1,-4]", "output": "[[-1,-1,2],[-1,0,1]]", "explanation": null}, {"input": "nums = [0,1,1]", "output": "[]", "explanation": "No triplet sums to 0."}]',
 '[{"args": [[-1,0,1,2,-1,-4]], "expected": [[-1,-1,2],[-1,0,1]]}, {"args": [[0,1,1]], "expected": []}, {"args": [[0,0,0]], "expected": [[0,0,0]]}]',
 ARRAY['array','two_pointer','blind75'], 'blind75', 'core', '{"array": true}',
 'threeSum', E'def threeSum(nums):\n    pass\n',
 ARRAY['Sort the array first — this makes both skipping duplicates and the two-pointer scan possible.', 'Fix one number, then use two pointers moving inward from the two ends of the remaining sorted range to find pairs that complete the sum.'],
 NULL),

('Coin Change', 'medium', 'dp',
 'You are given a list of coin denominations and a target amount. Return the fewest number of coins needed to make up that amount using any combination of the given coins (unlimited supply of each). If the amount cannot be made up, return -1.',
 E'- 1 <= coins.length <= 12\n- 1 <= coins[i] <= 2^31 - 1\n- 0 <= amount <= 10^4',
 '[{"input": "coins = [1,2,5], amount = 11", "output": "3", "explanation": "11 = 5 + 5 + 1."}, {"input": "coins = [2], amount = 3", "output": "-1", "explanation": "3 cannot be made from only 2s."}]',
 '[{"args": [[1,2,5], 11], "expected": 3}, {"args": [[2], 3], "expected": -1}, {"args": [[1], 0], "expected": 0}]',
 ARRAY['dp','blind75'], 'blind75', 'core', '{"dp_1d": true}',
 'coinChange', E'def coinChange(coins, amount):\n    pass\n',
 ARRAY['Let dp[a] be the fewest coins needed for amount a. dp[0] = 0.', 'For each amount from 1 up to the target, try every coin and take the best dp[a - coin] + 1.'],
 NULL),

('House Robber', 'medium', 'dp',
 'You are a robber planning to rob houses along a street, where the value at each position is the amount of money in that house. You cannot rob two adjacent houses (it triggers an alarm). Return the maximum amount you can rob.',
 E'- 1 <= nums.length <= 100\n- 0 <= nums[i] <= 400',
 '[{"input": "nums = [1,2,3,1]", "output": "4", "explanation": "Rob house 0 (1) and house 2 (3): 1 + 3 = 4."}, {"input": "nums = [2,7,9,3,1]", "output": "12", "explanation": "Rob houses 0, 2, and 4: 2 + 9 + 1 = 12."}]',
 '[{"args": [[1,2,3,1]], "expected": 4}, {"args": [[2,7,9,3,1]], "expected": 12}, {"args": [[5]], "expected": 5}]',
 ARRAY['dp','blind75'], 'blind75', 'core', '{"dp_1d": true}',
 'rob', E'def rob(nums):\n    pass\n',
 ARRAY['At each house, you either skip it (keep the best total so far) or rob it (best total from two houses back, plus this house''s value).'],
 NULL),

('Number of Islands', 'medium', 'graph',
 'Given a 2D grid of 0s (water) and 1s (land), return the number of islands. An island is a group of 1s connected horizontally or vertically, surrounded by water.',
 E'- 1 <= grid.length, grid[i].length <= 300\n- Each cell is 0 or 1.',
 '[{"input": "grid = [[1,1,0,0],[1,1,0,0],[0,0,1,0],[0,0,0,1]]", "output": "3", "explanation": null}, {"input": "grid = [[1,0],[0,1]]", "output": "2", "explanation": "The two land cells are not adjacent, so they are separate islands."}]',
 '[{"args": [[[1,1,0,0],[1,1,0,0],[0,0,1,0],[0,0,0,1]]], "expected": 3}, {"args": [[[1,0],[0,1]]], "expected": 2}, {"args": [[[0,0],[0,0]]], "expected": 0}]',
 ARRAY['graph','blind75'], 'blind75', 'core', '{"graph": true}',
 'numIslands', E'def numIslands(grid):\n    pass\n',
 ARRAY['Scan every cell; whenever you find an unvisited land cell, that''s a brand new island — flood-fill (BFS or DFS) to mark every connected land cell as visited.'],
 NULL),

('Course Schedule', 'medium', 'graph',
 'There are numCourses courses, labeled 0 to numCourses - 1. You are given a list of prerequisite pairs [a, b] meaning you must take course b before course a. Return true if it is possible to finish all courses, and false if there is a cycle making it impossible.',
 E'- 1 <= numCourses <= 2000\n- 0 <= prerequisites.length <= 5000',
 '[{"input": "numCourses = 2, prerequisites = [[1,0]]", "output": "true", "explanation": "Take course 0, then course 1."}, {"input": "numCourses = 2, prerequisites = [[1,0],[0,1]]", "output": "false", "explanation": "Course 0 needs course 1 and course 1 needs course 0 — a cycle."}]',
 '[{"args": [2, [[1,0]]], "expected": true}, {"args": [2, [[1,0],[0,1]]], "expected": false}, {"args": [1, []], "expected": true}]',
 ARRAY['graph','blind75'], 'blind75', 'core', '{"graph": true}',
 'canFinish', E'def canFinish(numCourses, prerequisites):\n    pass\n',
 ARRAY['Model this as a directed graph: an edge from a course to each of its prerequisites.', 'The courses can all be finished exactly when this graph has no cycle — try a DFS that tracks nodes currently being visited on the current path.'],
 NULL),

('Merge Two Sorted Lists', 'easy', 'linked_list',
 'You are given two sorted lists of integers, representing two sorted linked lists in order. Merge them into a single sorted list and return it as a list of values.',
 E'- 0 <= list1.length, list2.length <= 50\n- -100 <= values <= 100',
 '[{"input": "list1 = [1,2,4], list2 = [1,3,4]", "output": "[1,1,2,3,4,4]", "explanation": null}, {"input": "list1 = [], list2 = []", "output": "[]", "explanation": null}]',
 '[{"args": [[1,2,4], [1,3,4]], "expected": [1,1,2,3,4,4]}, {"args": [[], []], "expected": []}, {"args": [[], [0]], "expected": [0]}]',
 ARRAY['linked_list','blind75'], 'blind75', 'core', '{"linked_list": true}',
 'mergeTwoLists', E'def mergeTwoLists(list1, list2):\n    pass\n',
 ARRAY['Walk both lists with two pointers, always taking the smaller current value next.', 'Once one list runs out, append whatever remains of the other.'],
 NULL),

('Maximum Depth of Binary Tree', 'easy', 'trees',
 'Given the root of a binary tree, return its maximum depth (the number of nodes along the longest path from the root down to the farthest leaf). For judging, the tree is passed as a level-order list with None for missing nodes.',
 E'- The number of nodes is in the range [0, 10^4].\n- -100 <= Node.val <= 100',
 '[{"input": "root = [3,9,20,null,null,15,7]", "output": "3", "explanation": null}, {"input": "root = [1,null,2]", "output": "2", "explanation": null}]',
 '[{"args": [[3,9,20,null,null,15,7]], "expected": 3}, {"args": [[1,null,2]], "expected": 2}, {"args": [[]], "expected": 0}]',
 ARRAY['tree','blind75'], 'blind75', 'core', '{"tree": true}',
 'maxDepth', E'def maxDepth(values):\n    pass\n',
 ARRAY['The depth of a tree is 1 plus the deeper of its two subtrees'' depths — this is naturally recursive.'],
 NULL),

('Same Tree', 'easy', 'trees',
 'Given the roots of two binary trees, return true if they are structurally identical and every corresponding node has the same value. Both trees are passed as level-order lists with None for missing nodes, for judging.',
 E'- The number of nodes in both trees is in the range [0, 100].\n- -10^4 <= Node.val <= 10^4',
 '[{"input": "p = [1,2,3], q = [1,2,3]", "output": "true", "explanation": null}, {"input": "p = [1,2], q = [1,null,2]", "output": "false", "explanation": "In p, 2 is a left child; in q, 2 is a right child."}]',
 '[{"args": [[1,2,3], [1,2,3]], "expected": true}, {"args": [[1,2], [1,null,2]], "expected": false}, {"args": [[1,2,1], [1,1,2]], "expected": false}]',
 ARRAY['tree','blind75'], 'blind75', 'core', '{"tree": true}',
 'isSameTree', E'def isSameTree(p, q):\n    pass\n',
 ARRAY['Compare the two roots'' values, then recursively check that both left subtrees match and both right subtrees match.'],
 NULL),

('Validate Binary Search Tree', 'medium', 'trees',
 'Given the root of a binary tree, determine if it is a valid binary search tree (BST): every node''s value is strictly greater than all values in its left subtree and strictly less than all values in its right subtree. For judging, the tree is passed as a level-order list with None for missing nodes.',
 E'- The number of nodes is in the range [1, 10^4].\n- -2^31 <= Node.val <= 2^31 - 1',
 '[{"input": "root = [2,1,3]", "output": "true", "explanation": null}, {"input": "root = [5,1,4,null,null,3,6]", "output": "false", "explanation": "Node 4 is in the root''s right subtree, so every value under it must exceed 5. Its child 3 does not, so the tree is invalid."}]',
 '[{"args": [[2,1,3]], "expected": true}, {"args": [[5,1,4,null,null,3,6]], "expected": false}, {"args": [[1]], "expected": true}]',
 ARRAY['tree','blind75'], 'blind75', 'core', '{"tree": true}',
 'isValidBST', E'def isValidBST(values):\n    pass\n',
 ARRAY['A node alone doesn''t tell you if the tree is valid — you need to track the valid (low, high) range allowed at each position as you recurse down.', 'The left child inherits the same lower bound but its parent''s value becomes the new upper bound; the right child is the mirror.'],
 NULL),

('Kth Largest Element in an Array', 'medium', 'heap',
 'Given a list of integers and an integer k, return the kth largest element in the list (the kth largest in sorted order, not the kth distinct value).',
 E'- 1 <= k <= nums.length <= 10^5\n- -10^4 <= nums[i] <= 10^4',
 '[{"input": "nums = [3,2,1,5,6,4], k = 2", "output": "5", "explanation": null}, {"input": "nums = [3,2,3,1,2,4,5,5,6], k = 4", "output": "4", "explanation": null}]',
 '[{"args": [[3,2,1,5,6,4], 2], "expected": 5}, {"args": [[3,2,3,1,2,4,5,5,6], 4], "expected": 4}, {"args": [[1], 1], "expected": 1}]',
 ARRAY['heap','blind75'], 'blind75', 'core', '{"array": true}',
 'findKthLargest', E'def findKthLargest(nums, k):\n    pass\n',
 ARRAY['A min-heap of size k, keeping only the k largest values seen so far, gives you the answer at its top once you''ve scanned everything.'],
 'Can you solve it without sorting the entire array, in better than O(n log n)?'),

('Longest Substring Without Repeating Characters', 'medium', 'sliding_window',
 'Given a string s, find the length of the longest substring without repeating characters.',
 E'- 0 <= s.length <= 5 * 10^4\n- s consists of English letters, digits, symbols and spaces.',
 '[{"input": "s = \"abcabcbb\"", "output": "3", "explanation": "The answer is \"abc\", with length 3."}, {"input": "s = \"bbbbb\"", "output": "1", "explanation": "The answer is \"b\", with length 1."}, {"input": "s = \"pwwkew\"", "output": "3", "explanation": "The answer is \"wke\", with length 3."}]',
 '[{"args": ["abcabcbb"], "expected": 3}, {"args": ["bbbbb"], "expected": 1}, {"args": ["pwwkew"], "expected": 3}]',
 ARRAY['string','sliding_window','blind75'], 'blind75', 'core', '{"array": true}',
 'lengthOfLongestSubstring', E'def lengthOfLongestSubstring(s):\n    pass\n',
 ARRAY['Keep a sliding window [start, i] with no repeats, and a map of each character''s most recent index.', 'When you see a character already in the window, jump start to just past its previous occurrence.'],
 NULL);

-- Blind 75 batch 2 (arrays/binary-search/dp/intervals)
INSERT INTO problems (title, difficulty, pattern, statement, constraints, examples, testcases, tags, source, visualization_tier, visualization_meta, function_name, starter_code, hints, follow_up) VALUES

('Maximum Product Subarray', 'medium', 'array',
 'Given a list of integers, find a contiguous subarray that has the largest product, and return that product.',
 E'- 1 <= nums.length <= 2 * 10^4\n- -10 <= nums[i] <= 10',
 '[{"input": "nums = [2,3,-2,4]", "output": "6", "explanation": "[2,3] has the largest product, 6."}, {"input": "nums = [-2,0,-1]", "output": "0", "explanation": "The result cannot be 2, because [-2,-1] is not contiguous through the 0."}]',
 '[{"args": [[2,3,-2,4]], "expected": 6}, {"args": [[-2,0,-1]], "expected": 0}, {"args": [[-2]], "expected": -2}]',
 ARRAY['array','blind75'], 'blind75', 'core', '{"array": true}',
 'maxProduct', E'def maxProduct(nums):\n    pass\n',
 ARRAY['A negative number can flip the smallest running product into the largest one — track both a running max and a running min product as you scan.'],
 NULL),

('Find Minimum in Rotated Sorted Array', 'medium', 'binary_search',
 'You are given an array of unique integers that was originally sorted in ascending order, then rotated at some unknown pivot. Return the minimum element.',
 E'- 1 <= nums.length <= 5000\n- All values are unique.',
 '[{"input": "nums = [3,4,5,1,2]", "output": "1", "explanation": null}, {"input": "nums = [4,5,6,7,0,1,2]", "output": "0", "explanation": null}]',
 '[{"args": [[3,4,5,1,2]], "expected": 1}, {"args": [[4,5,6,7,0,1,2]], "expected": 0}, {"args": [[11,13,15,17]], "expected": 11}]',
 ARRAY['array','binary_search','blind75'], 'blind75', 'core', '{"array": true}',
 'findMin', E'def findMin(nums):\n    pass\n',
 ARRAY['Compare the middle element to the rightmost element — that tells you which half is the rotated (unsorted) side that could still contain the minimum.'],
 NULL),

('Search in Rotated Sorted Array', 'medium', 'binary_search',
 'You are given an array of unique integers, sorted in ascending order but then rotated at some unknown pivot, and a target value. Return the index of target if it exists, otherwise -1.',
 E'- 1 <= nums.length <= 5000\n- All values are unique.',
 '[{"input": "nums = [4,5,6,7,0,1,2], target = 0", "output": "4", "explanation": null}, {"input": "nums = [4,5,6,7,0,1,2], target = 3", "output": "-1", "explanation": null}]',
 '[{"args": [[4,5,6,7,0,1,2], 0], "expected": 4}, {"args": [[4,5,6,7,0,1,2], 3], "expected": -1}, {"args": [[1], 0], "expected": -1}]',
 ARRAY['array','binary_search','blind75'], 'blind75', 'core', '{"array": true}',
 'search', E'def search(nums, target):\n    pass\n',
 ARRAY['At each step, at least one half of the array (split at the midpoint) is properly sorted — figure out which half that is, then check if the target falls in its range.'],
 NULL),

('Container With Most Water', 'medium', 'two_pointer',
 'You are given a list of non-negative integers representing vertical line heights at each position. Choose two lines that, together with the x-axis, form a container. Return the maximum amount of water the container can hold.',
 E'- 2 <= heights.length <= 10^5\n- 0 <= heights[i] <= 10^4',
 '[{"input": "heights = [1,8,6,2,5,4,8,3,7]", "output": "49", "explanation": "The lines at index 1 (height 8) and index 8 (height 7) hold min(8,7) * (8-1) = 49."}, {"input": "heights = [1,1]", "output": "1", "explanation": null}]',
 '[{"args": [[1,8,6,2,5,4,8,3,7]], "expected": 49}, {"args": [[1,1]], "expected": 1}, {"args": [[4,3,2,1,4]], "expected": 16}]',
 ARRAY['array','two_pointer','blind75'], 'blind75', 'core', '{"array": true}',
 'maxArea', E'def maxArea(heights):\n    pass\n',
 ARRAY['Start with the widest possible container (pointers at both ends) and move whichever pointer is at the shorter line inward — moving the taller one can only ever hurt you.'],
 NULL),

('Number of 1 Bits', 'easy', 'bit_manipulation',
 'Given an unsigned integer, return the number of 1 bits in its binary representation (the Hamming weight).',
 E'- 0 <= n <= 2^31 - 1',
 '[{"input": "n = 11", "output": "3", "explanation": "11 in binary is 1011, which has three 1 bits."}, {"input": "n = 128", "output": "1", "explanation": "128 in binary is 10000000."}]',
 '[{"args": [11], "expected": 3}, {"args": [128], "expected": 1}, {"args": [0], "expected": 0}]',
 ARRAY['bit_manipulation','blind75'], 'blind75', 'core', '{}',
 'hammingWeight', E'def hammingWeight(n):\n    pass\n',
 ARRAY['n & (n - 1) clears the lowest set bit — counting how many times you can do that before reaching 0 gives you the answer.'],
 NULL),

('Counting Bits', 'easy', 'bit_manipulation',
 'Given an integer n, return a list ans of length n + 1 where ans[i] is the number of 1 bits in the binary representation of i, for every i from 0 to n.',
 E'- 0 <= n <= 10^5',
 '[{"input": "n = 2", "output": "[0,1,1]", "explanation": "0 -> 0, 1 -> 1, 2 (10) -> 1."}, {"input": "n = 5", "output": "[0,1,1,2,1,2]", "explanation": null}]',
 '[{"args": [2], "expected": [0,1,1]}, {"args": [5], "expected": [0,1,1,2,1,2]}, {"args": [0], "expected": [0]}]',
 ARRAY['bit_manipulation','dp','blind75'], 'blind75', 'core', '{"array": true}',
 'countBits', E'def countBits(n):\n    pass\n',
 ARRAY['The bit count of i is the bit count of i // 2, plus 1 if i is odd — build the answer up from smaller values you''ve already computed.'],
 NULL),

('Missing Number', 'easy', 'bit_manipulation',
 'Given a list containing n distinct numbers taken from the range [0, n], return the one number in that range that is missing from the list.',
 E'- n == nums.length\n- 1 <= n <= 10^4\n- All values in nums are unique and in the range [0, n].',
 '[{"input": "nums = [3,0,1]", "output": "2", "explanation": "n = 3, and the range [0,3] is missing 2."}, {"input": "nums = [9,6,4,2,3,5,7,0,1]", "output": "8", "explanation": null}]',
 '[{"args": [[3,0,1]], "expected": 2}, {"args": [[9,6,4,2,3,5,7,0,1]], "expected": 8}, {"args": [[0]], "expected": 1}]',
 ARRAY['array','bit_manipulation','blind75'], 'blind75', 'core', '{"array": true}',
 'missingNumber', E'def missingNumber(nums):\n    pass\n',
 ARRAY['The sum of every integer from 0 to n has a simple closed form — subtracting the actual sum of nums from it leaves exactly the missing number.'],
 NULL),

('Longest Increasing Subsequence', 'medium', 'dp',
 'Given a list of integers, return the length of the longest strictly increasing subsequence (elements don''t need to be contiguous, just in increasing order and in their original relative order).',
 E'- 1 <= nums.length <= 2500\n- -10^4 <= nums[i] <= 10^4',
 '[{"input": "nums = [10,9,2,5,3,7,101,18]", "output": "4", "explanation": "The longest increasing subsequence is [2,3,7,101], or [2,3,7,18]."}, {"input": "nums = [7,7,7,7]", "output": "1", "explanation": "Strictly increasing means no repeats count as progress."}]',
 '[{"args": [[10,9,2,5,3,7,101,18]], "expected": 4}, {"args": [[0,1,0,3,2,3]], "expected": 4}, {"args": [[7,7,7,7]], "expected": 1}]',
 ARRAY['dp','blind75'], 'blind75', 'core', '{"array": true}',
 'lengthOfLIS', E'def lengthOfLIS(nums):\n    pass\n',
 ARRAY['A naive dp[i] = "longest subsequence ending at i" works in O(n^2).', 'For an O(n log n) approach, maintain a list of the smallest possible tail value for an increasing subsequence of each length, and binary search into it as you scan.'],
 'Can you get this down to O(n log n)?'),

('Word Break', 'medium', 'dp',
 'Given a string s and a list of words wordDict, return true if s can be split into a sequence of one or more words that all appear in wordDict. The same word from the dictionary may be reused as many times as needed.',
 E'- 1 <= s.length <= 300\n- 1 <= wordDict.length <= 1000',
 '[{"input": "s = \"leetcode\", wordDict = [\"leet\",\"code\"]", "output": "true", "explanation": "\"leetcode\" splits into \"leet\" + \"code\"."}, {"input": "s = \"catsandog\", wordDict = [\"cats\",\"dog\",\"sand\",\"and\",\"cat\"]", "output": "false", "explanation": null}]',
 '[{"args": ["leetcode", ["leet","code"]], "expected": true}, {"args": ["applepenapple", ["apple","pen"]], "expected": true}, {"args": ["catsandog", ["cats","dog","sand","and","cat"]], "expected": false}]',
 ARRAY['dp','string','blind75'], 'blind75', 'core', '{"array": true}',
 'wordBreak', E'def wordBreak(s, wordDict):\n    pass\n',
 ARRAY['Let dp[i] mean "the prefix s[:i] can be fully segmented." dp[0] is true (the empty prefix).', 'dp[i] is true if there''s some earlier split point j where dp[j] is true and s[j:i] is a dictionary word.'],
 NULL),

('House Robber II', 'medium', 'dp',
 'Same rules as robbing houses along a street (no two adjacent houses), except the houses are arranged in a circle — the first and last houses are now also adjacent to each other. Return the maximum amount you can rob.',
 E'- 1 <= nums.length <= 100\n- 0 <= nums[i] <= 1000',
 '[{"input": "nums = [2,3,2]", "output": "3", "explanation": "Robbing houses 0 and 2 is not allowed since they''re adjacent in the circle; the best is house 1 alone, or house 0 alone — 3 is the max (house 1)."}, {"input": "nums = [1,2,3,1]", "output": "4", "explanation": "Rob houses 0 and 2: 1 + 3 = 4."}]',
 '[{"args": [[2,3,2]], "expected": 3}, {"args": [[1,2,3,1]], "expected": 4}, {"args": [[1,2,3]], "expected": 3}]',
 ARRAY['dp','blind75'], 'blind75', 'core', '{"array": true}',
 'rob2', E'def rob2(nums):\n    pass\n',
 ARRAY['Because the first and last houses can''t both be robbed, the answer is just the better of two non-circular House Robber runs: one excluding the first house, one excluding the last.'],
 NULL),

('Jump Game', 'medium', 'greedy',
 'Given a list of non-negative integers where each value is the maximum jump length from that position, starting at index 0, return true if you can reach the last index.',
 E'- 1 <= nums.length <= 10^4\n- 0 <= nums[i] <= 10^5',
 '[{"input": "nums = [2,3,1,1,4]", "output": "true", "explanation": "Jump 1 step to index 1, then 3 steps to the last index."}, {"input": "nums = [3,2,1,0,4]", "output": "false", "explanation": "You always land on index 3, whose jump length is 0, so index 4 is unreachable."}]',
 '[{"args": [[2,3,1,1,4]], "expected": true}, {"args": [[3,2,1,0,4]], "expected": false}, {"args": [[0]], "expected": true}]',
 ARRAY['array','greedy','blind75'], 'blind75', 'core', '{"array": true}',
 'canJump', E'def canJump(nums):\n    pass\n',
 ARRAY['Track the farthest index reachable so far as you scan left to right. If you ever reach a position beyond that farthest point, you''re stuck.'],
 NULL),

('Unique Paths', 'medium', 'dp',
 'A robot sits at the top-left corner of an m x n grid and can only move right or down. Return the number of distinct paths to the bottom-right corner.',
 E'- 1 <= m, n <= 100',
 '[{"input": "m = 3, n = 7", "output": "28", "explanation": null}, {"input": "m = 3, n = 2", "output": "3", "explanation": null}]',
 '[{"args": [3, 7], "expected": 28}, {"args": [3, 2], "expected": 3}, {"args": [1, 1], "expected": 1}]',
 ARRAY['dp','blind75'], 'blind75', 'core', '{"dp_1d": true}',
 'uniquePaths', E'def uniquePaths(m, n):\n    pass\n',
 ARRAY['The number of paths to any cell is the sum of the paths to the cell above it and the cell to its left — the first row and first column each only have exactly one path.'],
 NULL),

('Insert Interval', 'medium', 'intervals',
 'Given a list of non-overlapping intervals sorted by start time, and a new interval, insert the new interval and merge any overlaps so the result stays sorted and non-overlapping.',
 E'- 0 <= intervals.length <= 10^4\n- intervals is sorted by start time and has no overlaps.',
 '[{"input": "intervals = [[1,3],[6,9]], newInterval = [2,5]", "output": "[[1,5],[6,9]]", "explanation": null}, {"input": "intervals = [[1,2],[3,5],[6,7],[8,10],[12,16]], newInterval = [4,8]", "output": "[[1,2],[3,10],[12,16]]", "explanation": null}]',
 '[{"args": [[[1,3],[6,9]], [2,5]], "expected": [[1,5],[6,9]]}, {"args": [[[1,2],[3,5],[6,7],[8,10],[12,16]], [4,8]], "expected": [[1,2],[3,10],[12,16]]}, {"args": [[], [5,7]], "expected": [[5,7]]}]',
 ARRAY['intervals','blind75'], 'blind75', 'core', '{"array": true}',
 'insert', E'def insert(intervals, newInterval):\n    pass\n',
 ARRAY['Walk through in three phases: intervals entirely before the new one (copy as-is), intervals that overlap it (merge them all into one growing interval), then intervals entirely after (copy as-is).'],
 NULL),

('Merge Intervals', 'medium', 'intervals',
 'Given a list of intervals, merge all overlapping intervals and return the resulting list sorted in ascending order by start time.',
 E'- 1 <= intervals.length <= 10^4',
 '[{"input": "intervals = [[1,3],[2,6],[8,10],[15,18]]", "output": "[[1,6],[8,10],[15,18]]", "explanation": "[1,3] and [2,6] overlap, so they merge into [1,6]."}, {"input": "intervals = [[1,4],[4,5]]", "output": "[[1,5]]", "explanation": null}]',
 '[{"args": [[[1,3],[2,6],[8,10],[15,18]]], "expected": [[1,6],[8,10],[15,18]]}, {"args": [[[1,4],[4,5]]], "expected": [[1,5]]}, {"args": [[[1,4]]], "expected": [[1,4]]}]',
 ARRAY['intervals','blind75'], 'blind75', 'core', '{"array": true}',
 'merge', E'def merge(intervals):\n    pass\n',
 ARRAY['Sort the intervals by start time first — once sorted, any interval that needs merging will be adjacent to the one you''re currently building.'],
 NULL),

('Non-overlapping Intervals', 'medium', 'intervals',
 'Given a list of intervals, return the minimum number of intervals you need to remove so that the rest do not overlap.',
 E'- 1 <= intervals.length <= 10^5',
 '[{"input": "intervals = [[1,2],[2,3],[3,4],[1,3]]", "output": "1", "explanation": "Remove [1,3] and the rest don''t overlap."}, {"input": "intervals = [[1,2],[1,2],[1,2]]", "output": "2", "explanation": "Remove two of the three identical intervals."}]',
 '[{"args": [[[1,2],[2,3],[3,4],[1,3]]], "expected": 1}, {"args": [[[1,2],[1,2],[1,2]]], "expected": 2}, {"args": [[[1,2],[2,3]]], "expected": 0}]',
 ARRAY['intervals','greedy','blind75'], 'blind75', 'core', '{"array": true}',
 'eraseOverlapIntervals', E'def eraseOverlapIntervals(intervals):\n    pass\n',
 ARRAY['Sort by end time, not start time — greedily keep the interval that finishes earliest, since it leaves the most room for what comes after.'],
 NULL);

-- Blind 75 batch 3 (graphs/linked-list/matrix). Clone Graph and Linked List Cycle
-- Detection deliberately NOT included: their real I/O can't be judged meaningfully
-- through a plain args-in/JSON-out function call (see CLAUDE.md decision note).
INSERT INTO problems (title, difficulty, pattern, statement, constraints, examples, testcases, tags, source, visualization_tier, visualization_meta, function_name, starter_code, hints, follow_up) VALUES

('Rotting Oranges', 'medium', 'graph',
 'You are given a grid where each cell is 0 (empty), 1 (a fresh orange), or 2 (a rotten orange). Every minute, any fresh orange adjacent (up/down/left/right) to a rotten orange becomes rotten. Return the minimum number of minutes until no fresh orange remains, or -1 if that is impossible.',
 E'- 1 <= grid.length, grid[i].length <= 10\n- Each cell is 0, 1, or 2.',
 '[{"input": "grid = [[2,1,1],[1,1,0],[0,1,1]]", "output": "4", "explanation": null}, {"input": "grid = [[0,2]]", "output": "0", "explanation": "There are no fresh oranges, so 0 minutes are needed."}, {"input": "grid = [[1]]", "output": "-1", "explanation": "The one fresh orange has no rotten neighbor and can never rot."}]',
 '[{"args": [[[2,1,1],[1,1,0],[0,1,1]]], "expected": 4}, {"args": [[[0,2]]], "expected": 0}, {"args": [[[1]]], "expected": -1}]',
 ARRAY['graph','blind75'], 'blind75', 'core', '{"graph": true}',
 'orangesRotting', E'def orangesRotting(grid):\n    pass\n',
 ARRAY['This is a multi-source BFS: start the search from every rotten orange at once, not just one.', 'Each BFS "layer" you process corresponds to exactly one minute passing.'],
 NULL),

('Pacific Atlantic Water Flow', 'medium', 'graph',
 'You are given a grid of heights. The Pacific Ocean touches the top row and left column; the Atlantic touches the bottom row and right column. Water can flow from a cell to a neighboring cell only if the neighbor''s height is less than or equal to the current cell''s height. Return the coordinates [row, col] of every cell from which water can reach both oceans, sorted in ascending order (by row, then by column).',
 E'- 1 <= heights.length, heights[i].length <= 200',
 '[{"input": "heights = [[1,1],[1,1]]", "output": "[[0,0],[0,1],[1,0],[1,1]]", "explanation": "The grid is flat, so every cell can flow to both oceans."}, {"input": "heights = [[1]]", "output": "[[0,0]]", "explanation": "The single cell touches both oceans directly."}]',
 '[{"args": [[[1,1],[1,1]]], "expected": [[0,0],[0,1],[1,0],[1,1]]}, {"args": [[[1]]], "expected": [[0,0]]}, {"args": [[[3,3,3],[3,1,3],[3,3,3]]], "expected": [[0,0],[0,1],[0,2],[1,0],[1,2],[2,0],[2,1],[2,2]]}]',
 ARRAY['graph','blind75'], 'blind75', 'core', '{"graph": true}',
 'pacificAtlantic', E'def pacificAtlantic(heights):\n    pass\n',
 ARRAY['Instead of checking, for every cell, whether it can reach both oceans forward (slow), work backward: start a search from every Pacific-adjacent cell and every Atlantic-adjacent cell, moving only to neighbors of equal or greater height, and see which cells both searches reach.'],
 NULL),

('Longest Consecutive Sequence', 'medium', 'hashing',
 'Given an unsorted list of integers, return the length of the longest run of consecutive integers (they do not need to appear in order in the list).',
 E'- 0 <= nums.length <= 10^5',
 '[{"input": "nums = [100,4,200,1,3,2]", "output": "4", "explanation": "The longest consecutive run is [1,2,3,4]."}, {"input": "nums = [0,3,7,2,5,8,4,6,0,1]", "output": "9", "explanation": null}]',
 '[{"args": [[100,4,200,1,3,2]], "expected": 4}, {"args": [[0,3,7,2,5,8,4,6,0,1]], "expected": 9}, {"args": [[]], "expected": 0}]',
 ARRAY['array','hashing','blind75'], 'blind75', 'core', '{"hashmap": true}',
 'longestConsecutive', E'def longestConsecutive(nums):\n    pass\n',
 ARRAY['Put every number in a set for O(1) lookups.', 'Only start counting a run from a number that has no predecessor (n - 1) in the set — that guarantees you count each run exactly once, in O(n) overall.'],
 'Can you solve this in O(n) time, without sorting?'),

('Number of Connected Components in an Undirected Graph', 'medium', 'graph',
 'You are given n nodes labeled 0 to n - 1 and a list of undirected edges. Return the number of connected components in the graph.',
 E'- 1 <= n <= 2000',
 '[{"input": "n = 5, edges = [[0,1],[1,2],[3,4]]", "output": "2", "explanation": "{0,1,2} form one component and {3,4} form another."}, {"input": "n = 5, edges = [[0,1],[1,2],[2,3],[3,4]]", "output": "1", "explanation": null}]',
 '[{"args": [5, [[0,1],[1,2],[3,4]]], "expected": 2}, {"args": [5, [[0,1],[1,2],[2,3],[3,4]]], "expected": 1}, {"args": [3, []], "expected": 3}]',
 ARRAY['graph','blind75'], 'blind75', 'core', '{"graph": true}',
 'countComponents', E'def countComponents(n, edges):\n    pass\n',
 ARRAY['Union-Find (disjoint set union) is a natural fit: union the two endpoints of every edge, then count how many distinct roots remain.'],
 NULL),

('Graph Valid Tree', 'medium', 'graph',
 'Given n nodes labeled 0 to n - 1 and a list of undirected edges, return true if these edges form a valid tree (the graph is fully connected and contains no cycle).',
 E'- 1 <= n <= 2000',
 '[{"input": "n = 5, edges = [[0,1],[0,2],[0,3],[1,4]]", "output": "true", "explanation": null}, {"input": "n = 5, edges = [[0,1],[1,2],[2,3],[1,3],[1,4]]", "output": "false", "explanation": "There is a cycle among nodes 1, 2, and 3."}]',
 '[{"args": [5, [[0,1],[0,2],[0,3],[1,4]]], "expected": true}, {"args": [5, [[0,1],[1,2],[2,3],[1,3],[1,4]]], "expected": false}, {"args": [1, []], "expected": true}]',
 ARRAY['graph','blind75'], 'blind75', 'core', '{"graph": true}',
 'validTree', E'def validTree(n, edges):\n    pass\n',
 ARRAY['A valid tree on n nodes must have exactly n - 1 edges — check that first as a cheap early exit.', 'Then use Union-Find: if you ever try to union two nodes that already share a root, that''s a cycle.'],
 NULL),

('Meeting Rooms', 'easy', 'intervals',
 'Given a list of meeting time intervals, return true if a single person could attend every meeting (no two intervals overlap).',
 E'- 0 <= intervals.length <= 10^4',
 '[{"input": "intervals = [[0,30],[5,10],[15,20]]", "output": "false", "explanation": "[0,30] overlaps both other meetings."}, {"input": "intervals = [[7,10],[2,4]]", "output": "true", "explanation": null}]',
 '[{"args": [[[0,30],[5,10],[15,20]]], "expected": false}, {"args": [[[7,10],[2,4]]], "expected": true}, {"args": [[]], "expected": true}]',
 ARRAY['intervals','blind75'], 'blind75', 'core', '{"array": true}',
 'canAttendMeetings', E'def canAttendMeetings(intervals):\n    pass\n',
 ARRAY['Sort the intervals by start time — once sorted, any overlap must happen between consecutive intervals.'],
 NULL),

('Meeting Rooms II', 'medium', 'intervals',
 'Given a list of meeting time intervals, return the minimum number of meeting rooms required so that every meeting can be scheduled.',
 E'- 1 <= intervals.length <= 10^4',
 '[{"input": "intervals = [[0,30],[5,10],[15,20]]", "output": "2", "explanation": "[5,10] and [15,20] can share a room after [0,30] is elsewhere, but at most 2 meetings ever overlap at once."}, {"input": "intervals = [[7,10],[2,4]]", "output": "1", "explanation": null}]',
 '[{"args": [[[0,30],[5,10],[15,20]]], "expected": 2}, {"args": [[[7,10],[2,4]]], "expected": 1}, {"args": [[[1,5],[2,6],[3,7]]], "expected": 3}]',
 ARRAY['intervals','blind75'], 'blind75', 'core', '{"array": true}',
 'minMeetingRooms', E'def minMeetingRooms(intervals):\n    pass\n',
 ARRAY['Separate all start times and all end times into two sorted lists, then sweep through: every start needs a room, every end frees one up. Track the running count and its peak.'],
 NULL),

('Merge K Sorted Lists', 'hard', 'linked_list',
 'You are given k sorted lists of integers. Merge them all into one sorted list and return it.',
 E'- k == lists.length\n- 0 <= k <= 10^4\n- 0 <= each list''s length <= 500',
 '[{"input": "lists = [[1,4,5],[1,3,4],[2,6]]", "output": "[1,1,2,3,4,4,5,6]", "explanation": null}, {"input": "lists = []", "output": "[]", "explanation": null}]',
 '[{"args": [[[1,4,5],[1,3,4],[2,6]]], "expected": [1,1,2,3,4,4,5,6]}, {"args": [[]], "expected": []}, {"args": [[[],[1]]], "expected": [1]}]',
 ARRAY['linked_list','heap','blind75'], 'blind75', 'core', '{"linked_list": true}',
 'mergeKLists', E'def mergeKLists(lists):\n    pass\n',
 ARRAY['A min-heap holding the current front element of each list lets you always pull the smallest remaining value in O(log k) per step.'],
 NULL),

('Remove Nth Node From End of List', 'medium', 'linked_list',
 'Given a list of values representing a linked list, remove the nth node counting from the end of the list, and return the resulting list.',
 E'- The number of nodes is in the range [1, 30].\n- 1 <= n <= number of nodes',
 '[{"input": "values = [1,2,3,4,5], n = 2", "output": "[1,2,3,5]", "explanation": "The 2nd node from the end (value 4) is removed."}, {"input": "values = [1], n = 1", "output": "[]", "explanation": null}]',
 '[{"args": [[1,2,3,4,5], 2], "expected": [1,2,3,5]}, {"args": [[1], 1], "expected": []}, {"args": [[1,2], 1], "expected": [1]}]',
 ARRAY['linked_list','blind75'], 'blind75', 'core', '{"linked_list": true}',
 'removeNthFromEnd', E'def removeNthFromEnd(values, n):\n    pass\n',
 ARRAY['With a plain list you can compute the target index directly (length - n); in a real singly-linked list, the classic trick is two pointers n apart, moved together.'],
 'Could you do this in one pass through a real linked list, without knowing its length up front?'),

('Reorder List', 'medium', 'linked_list',
 'Given a list of values representing a linked list L0, L1, ..., Ln, reorder it in place to L0, Ln, L1, Ln-1, L2, Ln-2, ... and return the reordered list.',
 E'- The number of nodes is in the range [1, 5 * 10^4].',
 '[{"input": "values = [1,2,3,4]", "output": "[1,4,2,3]", "explanation": null}, {"input": "values = [1,2,3,4,5]", "output": "[1,5,2,4,3]", "explanation": null}]',
 '[{"args": [[1,2,3,4]], "expected": [1,4,2,3]}, {"args": [[1,2,3,4,5]], "expected": [1,5,2,4,3]}, {"args": [[1]], "expected": [1]}]',
 ARRAY['linked_list','blind75'], 'blind75', 'core', '{"linked_list": true}',
 'reorderList', E'def reorderList(values):\n    pass\n',
 ARRAY['Alternate taking from the front and the back of the remaining values.'],
 NULL),

('Set Matrix Zeroes', 'medium', 'array',
 'Given an m x n matrix, if an element is 0, set its entire row and column to 0. Return the modified matrix.',
 E'- m == matrix.length, n == matrix[0].length\n- 1 <= m, n <= 200',
 '[{"input": "matrix = [[1,1,1],[1,0,1],[1,1,1]]", "output": "[[1,0,1],[0,0,0],[1,0,1]]", "explanation": null}, {"input": "matrix = [[0,1,2,0],[3,4,5,2],[1,3,1,5]]", "output": "[[0,0,0,0],[0,4,5,0],[0,3,1,0]]", "explanation": null}]',
 '[{"args": [[[1,1,1],[1,0,1],[1,1,1]]], "expected": [[1,0,1],[0,0,0],[1,0,1]]}, {"args": [[[0,1,2,0],[3,4,5,2],[1,3,1,5]]], "expected": [[0,0,0,0],[0,4,5,0],[0,3,1,0]]}, {"args": [[[1]]], "expected": [[1]]}]',
 ARRAY['array','blind75'], 'blind75', 'core', '{"array": true}',
 'setZeroes', E'def setZeroes(matrix):\n    pass\n',
 ARRAY['First record which rows and which columns contain a 0 at all, then do a second pass to zero out anything in a marked row or column — this avoids zeroing cells that then falsely trigger more zeroing.'],
 'Could you do this using O(1) extra space, using parts of the matrix itself as markers?'),

('Spiral Matrix', 'medium', 'array',
 'Given an m x n matrix, return all its elements in spiral order (clockwise from the outside in).',
 E'- 1 <= m, n <= 10',
 '[{"input": "matrix = [[1,2,3],[4,5,6],[7,8,9]]", "output": "[1,2,3,6,9,8,7,4,5]", "explanation": null}, {"input": "matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]", "output": "[1,2,3,4,8,12,11,10,9,5,6,7]", "explanation": null}]',
 '[{"args": [[[1,2,3],[4,5,6],[7,8,9]]], "expected": [1,2,3,6,9,8,7,4,5]}, {"args": [[[1,2,3,4],[5,6,7,8],[9,10,11,12]]], "expected": [1,2,3,4,8,12,11,10,9,5,6,7]}, {"args": [[[1]]], "expected": [1]}]',
 ARRAY['array','blind75'], 'blind75', 'core', '{"array": true}',
 'spiralOrder', E'def spiralOrder(matrix):\n    pass\n',
 ARRAY['Peel the matrix layer by layer: take the whole top row, then the whole right column, then the bottom row reversed, then the left column reversed, and repeat on what''s left.'],
 NULL),

('Rotate Image', 'medium', 'array',
 'Given an n x n matrix, rotate it by 90 degrees clockwise and return the rotated matrix.',
 E'- n == matrix.length == matrix[i].length\n- 1 <= n <= 20',
 '[{"input": "matrix = [[1,2,3],[4,5,6],[7,8,9]]", "output": "[[7,4,1],[8,5,2],[9,6,3]]", "explanation": null}, {"input": "matrix = [[1,2],[3,4]]", "output": "[[3,1],[4,2]]", "explanation": null}]',
 '[{"args": [[[1,2,3],[4,5,6],[7,8,9]]], "expected": [[7,4,1],[8,5,2],[9,6,3]]}, {"args": [[[1,2],[3,4]]], "expected": [[3,1],[4,2]]}, {"args": [[[1]]], "expected": [[1]]}]',
 ARRAY['array','blind75'], 'blind75', 'core', '{"array": true}',
 'rotate', E'def rotate(matrix):\n    pass\n',
 ARRAY['A 90-degree clockwise rotation is the same as transposing the matrix (flip across the main diagonal) and then reversing each row.'],
 'Can you do it in place, using O(1) extra space?'),

('Word Search', 'medium', 'backtracking',
 'Given an m x n grid of letters and a word, return true if the word can be formed by a path of adjacent cells (horizontally or vertically), using each cell at most once.',
 E'- m == board.length, n == board[i].length\n- 1 <= m, n <= 6\n- 1 <= word.length <= 15',
 '[{"input": "board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"ABCCED\"", "output": "true", "explanation": null}, {"input": "board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"ABCB\"", "output": "false", "explanation": "The second B would need to reuse a cell already used for the first B."}]',
 '[{"args": [[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], "ABCCED"], "expected": true}, {"args": [[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], "ABCB"], "expected": false}, {"args": [[["A"]], "A"], "expected": true}]',
 ARRAY['backtracking','blind75'], 'blind75', 'core', '{"array": true}',
 'exist', E'def exist(board, word):\n    pass\n',
 ARRAY['Try starting the search from every cell that matches the word''s first letter.', 'Temporarily mark a cell as visited while exploring from it (e.g. overwrite it), and restore it when backtracking so other paths can still use it.'],
 NULL);

-- Blind 75 batch 4 (bit-manipulation/dp/string/tree)
INSERT INTO problems (title, difficulty, pattern, statement, constraints, examples, testcases, tags, source, visualization_tier, visualization_meta, function_name, starter_code, hints, follow_up) VALUES

('Sum of Two Integers', 'medium', 'bit_manipulation',
 'Given two integers a and b, return their sum without using the + or - operators.',
 E'- -1000 <= a, b <= 1000',
 '[{"input": "a = 1, b = 2", "output": "3", "explanation": null}, {"input": "a = 2, b = 3", "output": "5", "explanation": null}]',
 '[{"args": [1, 2], "expected": 3}, {"args": [2, 3], "expected": 5}, {"args": [0, 0], "expected": 0}]',
 ARRAY['bit_manipulation','blind75'], 'blind75', 'core', '{}',
 'getSum', E'def getSum(a, b):\n    pass\n',
 ARRAY['XOR adds two bits without carrying; AND-then-shift-left computes the carry those bits would produce. Repeat until there''s no carry left.'],
 NULL),

('Reverse Bits', 'easy', 'bit_manipulation',
 'Given a 32-bit unsigned integer, return the integer obtained by reversing the order of its bits.',
 E'- The input is exactly 32 bits.',
 '[{"input": "n = 1", "output": "2147483648", "explanation": "1 is 00000000000000000000000000000001 in binary; reversed it becomes 10000000000000000000000000000000, which is 2^31."}, {"input": "n = 0", "output": "0", "explanation": null}]',
 '[{"args": [1], "expected": 2147483648}, {"args": [0], "expected": 0}, {"args": [2], "expected": 1073741824}]',
 ARRAY['bit_manipulation','blind75'], 'blind75', 'core', '{}',
 'reverseBits', E'def reverseBits(n):\n    pass\n',
 ARRAY['Peel off each of the 32 bits one at a time from the input, and place it into the mirrored position of the result.'],
 NULL),

('Combination Sum IV', 'medium', 'dp',
 'Given a list of distinct positive integers and a target, return the number of possible ordered combinations that add up to target (the same number can be used multiple times, and different orderings count as different combinations).',
 E'- 1 <= nums.length <= 200\n- 1 <= target <= 1000',
 '[{"input": "nums = [1,2,3], target = 4", "output": "7", "explanation": "The 7 ordered combinations are (1,1,1,1),(1,1,2),(1,2,1),(2,1,1),(2,2),(1,3),(3,1)."}, {"input": "nums = [9], target = 3", "output": "0", "explanation": null}]',
 '[{"args": [[1,2,3], 4], "expected": 7}, {"args": [[9], 3], "expected": 0}, {"args": [[1], 1], "expected": 1}]',
 ARRAY['dp','blind75'], 'blind75', 'core', '{"dp_1d": true}',
 'combinationSum4', E'def combinationSum4(nums, target):\n    pass\n',
 ARRAY['Let dp[t] be the number of ordered combinations summing to t. dp[0] = 1 (the empty combination).', 'For each target value from 1 upward, try placing each number last and add in dp[t - num].'],
 NULL),

('Decode Ways', 'medium', 'dp',
 'A message of digits can be decoded where ''1''-''9'' map to letters ''A''-''I'' individually, and ''10''-''26'' also map to letters ''J''-''Z'' as two-digit codes. Given a string of digits, return the number of ways it can be decoded. A leading zero in any group makes that grouping invalid.',
 E'- 1 <= s.length <= 100\n- s consists of digits only.',
 '[{"input": "s = \"12\"", "output": "2", "explanation": "It can decode as \"AB\" (1,2) or \"L\" (12)."}, {"input": "s = \"226\"", "output": "3", "explanation": "\"BZ\" (2,26), \"VF\" (22,6), or \"BBF\" (2,2,6)."}]',
 '[{"args": ["12"], "expected": 2}, {"args": ["226"], "expected": 3}, {"args": ["06"], "expected": 0}]',
 ARRAY['dp','string','blind75'], 'blind75', 'core', '{"dp_1d": true}',
 'numDecodings', E'def numDecodings(s):\n    pass\n',
 ARRAY['At each position, you can either decode the current single digit alone (if it''s not ''0''), or combine it with the previous digit as a two-digit code (if that value is between 10 and 26).'],
 NULL),

('Longest Repeating Character Replacement', 'medium', 'sliding_window',
 'Given a string s and an integer k, you may replace up to k characters in the string with any other uppercase letter. Return the length of the longest substring you can make consist of a single repeated letter after doing so.',
 E'- 1 <= s.length <= 10^5\n- s consists of uppercase English letters only.',
 '[{"input": "s = \"ABAB\", k = 2", "output": "4", "explanation": "Replace both A''s or both B''s to get \"AAAA\" or \"BBBB\"."}, {"input": "s = \"AABABBA\", k = 1", "output": "4", "explanation": null}]',
 '[{"args": ["ABAB", 2], "expected": 4}, {"args": ["AABABBA", 1], "expected": 4}, {"args": ["A", 0], "expected": 1}]',
 ARRAY['sliding_window','string','blind75'], 'blind75', 'core', '{"array": true}',
 'characterReplacement', E'def characterReplacement(s, k):\n    pass\n',
 ARRAY['Keep a sliding window and track the count of the most frequent letter inside it. If (window size - most frequent count) exceeds k, the window needs more than k replacements, so shrink it from the left.'],
 NULL),

('Minimum Window Substring', 'hard', 'sliding_window',
 'Given two strings s and t, return the shortest substring of s that contains every character of t (including duplicates). Return an empty string if no such substring exists.',
 E'- 1 <= s.length, t.length <= 10^5',
 '[{"input": "s = \"ADOBECODEBANC\", t = \"ABC\"", "output": "\"BANC\"", "explanation": "\"BANC\" is the shortest substring containing A, B, and C."}, {"input": "s = \"a\", t = \"aa\"", "output": "\"\"", "explanation": "s only has one ''a'', but t needs two."}]',
 '[{"args": ["ADOBECODEBANC", "ABC"], "expected": "BANC"}, {"args": ["a", "a"], "expected": "a"}, {"args": ["a", "aa"], "expected": ""}]',
 ARRAY['sliding_window','string','blind75'], 'blind75', 'core', '{"array": true}',
 'minWindow', E'def minWindow(s, t):\n    pass\n',
 ARRAY['Expand a window over s until it contains every character t needs, then shrink it from the left as far as possible while it''s still valid, recording the shortest valid window seen.'],
 NULL),

('Valid Anagram', 'easy', 'hashing',
 'Given two strings s and t, return true if t is an anagram of s (uses exactly the same letters, same counts, in any order).',
 E'- 1 <= s.length, t.length <= 5 * 10^4\n- s and t consist of lowercase English letters.',
 '[{"input": "s = \"anagram\", t = \"nagaram\"", "output": "true", "explanation": null}, {"input": "s = \"rat\", t = \"car\"", "output": "false", "explanation": null}]',
 '[{"args": ["anagram", "nagaram"], "expected": true}, {"args": ["rat", "car"], "expected": false}, {"args": ["a", "ab"], "expected": false}]',
 ARRAY['hashing','string','blind75'], 'blind75', 'core', '{"hashmap": true}',
 'isAnagram', E'def isAnagram(s, t):\n    pass\n',
 ARRAY['Two strings are anagrams exactly when they have the same letter counts — sorting both and comparing, or comparing letter-frequency counts, both work.'],
 NULL),

('Valid Palindrome', 'easy', 'two_pointer',
 'Given a string, return true if it reads the same forward and backward after removing all non-alphanumeric characters and ignoring case.',
 E'- 1 <= s.length <= 2 * 10^5',
 '[{"input": "s = \"A man, a plan, a canal: Panama\"", "output": "true", "explanation": "After filtering: \"amanaplanacanalpanama\", which is a palindrome."}, {"input": "s = \"race a car\"", "output": "false", "explanation": null}]',
 '[{"args": ["A man, a plan, a canal: Panama"], "expected": true}, {"args": ["race a car"], "expected": false}, {"args": [" "], "expected": true}]',
 ARRAY['two_pointer','string','blind75'], 'blind75', 'core', '{"array": true}',
 'isPalindrome', E'def isPalindrome(s):\n    pass\n',
 ARRAY['Filter out non-alphanumeric characters and lowercase everything first, then just compare the result to its reverse (or walk two pointers inward).'],
 NULL),

('Longest Palindromic Substring', 'medium', 'string',
 'Given a string s, return the longest substring of s that is a palindrome.',
 E'- 1 <= s.length <= 1000',
 '[{"input": "s = \"cbbd\"", "output": "\"bb\"", "explanation": null}, {"input": "s = \"a\"", "output": "\"a\"", "explanation": null}]',
 '[{"args": ["cbbd"], "expected": "bb"}, {"args": ["a"], "expected": "a"}, {"args": ["racecar"], "expected": "racecar"}]',
 ARRAY['string','blind75'], 'blind75', 'core', '{"array": true}',
 'longestPalindrome', E'def longestPalindrome(s):\n    pass\n',
 ARRAY['Every palindrome has a center — either a single character (odd length) or a gap between two characters (even length). Try expanding outward from every possible center and track the widest one that holds.'],
 NULL),

('Palindromic Substrings', 'medium', 'string',
 'Given a string s, return the number of palindromic substrings in it (substrings that read the same forward and backward, counting each position/length as distinct even if the text repeats).',
 E'- 1 <= s.length <= 1000',
 '[{"input": "s = \"abc\"", "output": "3", "explanation": "\"a\", \"b\", \"c\" are each a palindrome of length 1."}, {"input": "s = \"aaa\"", "output": "6", "explanation": "\"a\",\"a\",\"a\",\"aa\",\"aa\",\"aaa\"."}]',
 '[{"args": ["abc"], "expected": 3}, {"args": ["aaa"], "expected": 6}, {"args": ["a"], "expected": 1}]',
 ARRAY['string','blind75'], 'blind75', 'core', '{"array": true}',
 'countSubstrings', E'def countSubstrings(s):\n    pass\n',
 ARRAY['Same center-expansion idea as finding the longest palindrome, but this time count every successful expansion instead of just tracking the longest one.'],
 NULL),

('Binary Tree Maximum Path Sum', 'hard', 'trees',
 'Given the root of a binary tree, a path is any sequence of nodes connected by edges, where each node appears at most once, and the path does not need to pass through the root. Return the maximum possible sum of node values along any path. For judging, the tree is passed as a level-order list with None for missing nodes.',
 E'- The number of nodes is in the range [1, 3 * 10^4].\n- -1000 <= Node.val <= 1000',
 '[{"input": "root = [1,2,3]", "output": "6", "explanation": "The path 2 -> 1 -> 3 has sum 6."}, {"input": "root = [-10,9,20,null,null,15,7]", "output": "42", "explanation": "The path 15 -> 20 -> 7 has sum 42."}]',
 '[{"args": [[1,2,3]], "expected": 6}, {"args": [[-10,9,20,null,null,15,7]], "expected": 42}, {"args": [[-3]], "expected": -3}]',
 ARRAY['tree','blind75'], 'blind75', 'core', '{"tree": true}',
 'maxPathSum', E'def maxPathSum(values):\n    pass\n',
 ARRAY['For each node, compute the best path that goes DOWN through just one side (needed so the parent can use this node in its own path). Separately, track the best path that goes through both sides of some node, as a candidate for the overall answer.', 'Negative subtree contributions should be treated as 0 — you''d simply not extend the path into them.'],
 NULL),

('Subtree of Another Tree', 'easy', 'trees',
 'Given the roots of two binary trees root and subRoot, return true if there is a subtree of root that is structurally identical to subRoot, with the same node values. Both trees are passed as level-order lists with None for missing nodes, for judging.',
 E'- The number of nodes in root is in the range [1, 2000].\n- The number of nodes in subRoot is in the range [1, 1000].',
 '[{"input": "root = [3,4,5,1,2], subRoot = [4,1,2]", "output": "true", "explanation": null}, {"input": "root = [3,4,5,1,2,null,null,null,null,0], subRoot = [4,1,2]", "output": "false", "explanation": "The matching subtree in root has an extra node that subRoot doesn''t have."}]',
 '[{"args": [[1,1], [1]], "expected": true}, {"args": [[1,1], [1,1]], "expected": true}, {"args": [[3,4,5,1,2], [4,1,3]], "expected": false}]',
 ARRAY['tree','blind75'], 'blind75', 'core', '{"tree": true}',
 'isSubtree', E'def isSubtree(root, subRoot):\n    pass\n',
 ARRAY['Write a helper that checks whether two trees are exactly the same.', 'Then check every node of root as a possible starting point: is the subtree rooted there identical to subRoot?'],
 NULL),

('Construct Binary Tree from Preorder and Inorder Traversal', 'medium', 'trees',
 'Given two integer lists preorder and inorder representing the preorder and inorder traversal of a binary tree (with unique values), reconstruct and return the tree. For judging, the tree is returned as a level-order list with None for missing nodes.',
 E'- 1 <= preorder.length <= 3000\n- All values are unique.',
 '[{"input": "preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]", "output": "[3,9,20,null,null,15,7]", "explanation": null}, {"input": "preorder = [-1], inorder = [-1]", "output": "[-1]", "explanation": null}]',
 '[{"args": [[3,9,20,15,7], [9,3,15,20,7]], "expected": [3,9,20,null,null,15,7]}, {"args": [[-1], [-1]], "expected": [-1]}, {"args": [[1,2], [2,1]], "expected": [1,2]}]',
 ARRAY['tree','blind75'], 'blind75', 'core', '{"tree": true}',
 'buildTree', E'def buildTree(preorder, inorder):\n    pass\n',
 ARRAY['The first element of preorder is always the root.', 'Find that value in inorder — everything to its left belongs to the left subtree, everything to its right belongs to the right subtree. Recurse on each side.'],
 NULL),

('Kth Smallest Element in a BST', 'medium', 'trees',
 'Given the root of a binary search tree and an integer k, return the kth smallest value in the tree (1-indexed). For judging, the tree is passed as a level-order list with None for missing nodes.',
 E'- The number of nodes is in the range [1, 10^4].\n- 1 <= k <= number of nodes',
 '[{"input": "root = [3,1,4,null,2], k = 1", "output": "1", "explanation": null}, {"input": "root = [5,3,6,2,4,null,null,1], k = 3", "output": "3", "explanation": null}]',
 '[{"args": [[3,1,4,null,2], 1], "expected": 1}, {"args": [[5,3,6,2,4,null,null,1], 3], "expected": 3}, {"args": [[1], 1], "expected": 1}]',
 ARRAY['tree','blind75'], 'blind75', 'core', '{"tree": true}',
 'kthSmallest', E'def kthSmallest(values, k):\n    pass\n',
 ARRAY['An in-order traversal of a BST visits nodes in ascending sorted order — the kth value visited is the answer.'],
 NULL),

('Lowest Common Ancestor of a Binary Search Tree', 'medium', 'trees',
 'Given a binary search tree and the values of two nodes p and q that both exist in the tree, return the value of their lowest common ancestor. For judging, the tree is passed as a level-order list with None for missing nodes.',
 E'- The number of nodes is in the range [2, 10^5].\n- All node values are unique.',
 '[{"input": "root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 8", "output": "6", "explanation": null}, {"input": "root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 4", "output": "2", "explanation": "Node 2 is an ancestor of node 4, and a node is allowed to be its own ancestor here."}]',
 '[{"args": [[6,2,8,0,4,7,9,null,null,3,5], 2, 8], "expected": 6}, {"args": [[6,2,8,0,4,7,9,null,null,3,5], 2, 4], "expected": 2}, {"args": [[2,1], 2, 1], "expected": 2}]',
 ARRAY['tree','blind75'], 'blind75', 'core', '{"tree": true}',
 'lowestCommonAncestor', E'def lowestCommonAncestor(values, p, q):\n    pass\n',
 ARRAY['Because it''s a BST, you can navigate without searching both subtrees: if both p and q are smaller than the current node, go left; if both are larger, go right; otherwise you''ve found the split point, which is the answer.'],
 NULL);

-- Blind 75 batch 5: ordering-ambiguous problems, each statement pins a canonical
-- output order so exact-match grading stays well-defined across different correct algorithms.
INSERT INTO problems (title, difficulty, pattern, statement, constraints, examples, testcases, tags, source, visualization_tier, visualization_meta, function_name, starter_code, hints, follow_up) VALUES

('Group Anagrams', 'medium', 'hashing',
 'Given a list of strings, group the anagrams together. Return the groups as a list of lists. For a well-defined judging order: sort the strings within each group alphabetically, and sort the groups themselves by their group''s sorted-letters signature.',
 E'- 1 <= strs.length <= 10^4\n- 0 <= strs[i].length <= 100\n- strs[i] consists of lowercase English letters.',
 '[{"input": "strs = [\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]", "output": "[[\"bat\"],[\"ate\",\"eat\",\"tea\"],[\"nat\",\"tan\"]]", "explanation": "\"eat\", \"tea\", and \"ate\" are anagrams of each other; \"tan\" and \"nat\" are anagrams of each other; \"bat\" is alone."}, {"input": "strs = [\"\"]", "output": "[[\"\"]]", "explanation": null}]',
 '[{"args": [["eat","tea","tan","ate","nat","bat"]], "expected": [["bat"],["ate","eat","tea"],["nat","tan"]]}, {"args": [[""]], "expected": [[""]]}, {"args": [["a"]], "expected": [["a"]]}]',
 ARRAY['hashing','blind75'], 'blind75', 'core', '{"hashmap": true}',
 'groupAnagrams', E'def groupAnagrams(strs):\n    pass\n',
 ARRAY['Two strings are anagrams exactly when their sorted letters are identical — use that sorted string as a hash map key to bucket words together.'],
 NULL),

('Top K Frequent Elements', 'medium', 'heap',
 'Given a list of integers and an integer k, return the k most frequent elements. For a well-defined judging order: break ties between equally frequent elements by returning the smaller value first.',
 E'- 1 <= nums.length <= 10^5\n- k is in the range [1, number of distinct elements].',
 '[{"input": "nums = [1,1,1,2,2,3], k = 2", "output": "[1,2]", "explanation": "1 appears 3 times, 2 appears 2 times — these are the 2 most frequent."}, {"input": "nums = [1], k = 1", "output": "[1]", "explanation": null}]',
 '[{"args": [[1,1,1,2,2,3], 2], "expected": [1,2]}, {"args": [[1], 1], "expected": [1]}, {"args": [[4,1,-1,2,-1,2,3], 2], "expected": [-1,2]}]',
 ARRAY['heap','hashing','blind75'], 'blind75', 'core', '{"hashmap": true}',
 'topKFrequent', E'def topKFrequent(nums, k):\n    pass\n',
 ARRAY['Count each value''s frequency with a hash map, then a heap (or bucket sort by frequency) gets you the k largest counts without fully sorting everything.'],
 'Can you do better than O(n log n) time, e.g. with bucket sort on frequency?'),

('Word Search II', 'hard', 'backtracking',
 'Given an m x n grid of letters and a list of words, return every word from the list that can be formed by a path of adjacent cells (horizontally or vertically), using each cell at most once per word. Return the found words sorted alphabetically.',
 E'- m == board.length, n == board[i].length\n- 1 <= m, n <= 12\n- 1 <= words.length <= 3 * 10^4',
 '[{"input": "board = [[\"a\",\"b\"],[\"c\",\"d\"]], words = [\"ab\",\"cd\",\"ac\",\"abcd\"]", "output": "[\"ab\",\"ac\",\"cd\"]", "explanation": "\"abcd\" would need a single path through all four letters in order, and no such path exists on this board."}, {"input": "board = [[\"a\",\"a\"]], words = [\"aa\"]", "output": "[\"aa\"]", "explanation": null}]',
 '[{"args": [[["a","b"],["c","d"]], ["ab","cd","ac","abcd"]], "expected": ["ab","ac","cd"]}, {"args": [[["a","a"]], ["aa"]], "expected": ["aa"]}, {"args": [[["a"]], ["a","b"]], "expected": ["a"]}]',
 ARRAY['backtracking','trie','blind75'], 'blind75', 'core', '{"array": true}',
 'findWords', E'def findWords(board, words):\n    pass\n',
 ARRAY['Building a trie out of all the words first lets a single grid traversal search for every word at once, instead of re-searching the whole board once per word.', 'Prune a search path as soon as it no longer matches any prefix in the trie.'],
 NULL),

('Alien Dictionary', 'hard', 'graph',
 'You are given a list of words from an alien language, sorted according to that language''s unknown letter order. Derive one valid ordering of the alphabet consistent with this sorted list, and return it as a string. If the input is impossible (contradictory, or a word appears before a proper prefix of itself), return an empty string. For a well-defined judging order, return the lexicographically smallest valid ordering among all that are valid.',
 E'- 1 <= words.length <= 100\n- Words consist of lowercase English letters.',
 '[{"input": "words = [\"ab\",\"ac\"]", "output": "\"abc\"", "explanation": "Comparing \"ab\" and \"ac\", b must come before c."}, {"input": "words = [\"abc\",\"ab\"]", "output": "\"\"", "explanation": "\"abc\" cannot come before its own prefix \"ab\" in a valid ordering."}]',
 '[{"args": [["ab","ac"]], "expected": "abc"}, {"args": [["z","x"]], "expected": "zx"}, {"args": [["abc","ab"]], "expected": ""}]',
 ARRAY['graph','blind75'], 'blind75', 'core', '{"graph": true}',
 'alienOrder', E'def alienOrder(words):\n    pass\n',
 ARRAY['Compare each pair of adjacent words to find the first position where they differ — that tells you one letter must come before another. Build this as a directed graph.', 'A topological sort of that graph gives a valid letter ordering; if the graph has a cycle, no valid ordering exists.'],
 NULL);

-- Backfill harness_type for rows inserted above without it set explicitly
-- (function-signature problems all have function_name set; everything else stays 'stdio').
UPDATE problems SET harness_type = 'function' WHERE function_name IS NOT NULL AND harness_type = 'stdio';

-- Blind 75 'design' problems: operations-sequence harness (harness_type='operations').
-- Each testcase is a static sequence of method calls + args + expected returns —
-- no result-chaining between calls yet (see CLAUDE.md decision note for what that blocks).
INSERT INTO problems (title, difficulty, pattern, statement, constraints, examples, testcases, tags, source, visualization_tier, visualization_meta, function_name, starter_code, hints, follow_up, harness_type) VALUES

('Implement Trie (Prefix Tree)', 'medium', 'trie',
 'Implement a Trie with an insert, search, and startsWith method. insert(word) adds a word to the trie. search(word) returns true only if word was previously inserted exactly. startsWith(prefix) returns true if any inserted word begins with prefix. For judging, each testcase is a sequence of operations (the first is always the constructor) with their arguments, and the expected return value of each (null for the constructor and for insert, which return nothing).',
 E'- 1 <= word.length, prefix.length <= 2000\n- word and prefix consist of lowercase English letters.\n- At most 3 * 10^4 total calls across insert, search, and startsWith.',
 '[{"input": "insert(\"apple\"); search(\"apple\"); search(\"app\"); startsWith(\"app\"); insert(\"app\"); search(\"app\")", "output": "[null, true, false, true, null, true]", "explanation": "\"app\" alone was never inserted until the second insert call, so the first search(\"app\") is false even though startsWith(\"app\") is true."}]',
 '[{"operations": ["Trie","insert","search","search","startsWith","insert","search"], "args": [[],["apple"],["apple"],["app"],["app"],["app"],["app"]], "expected": [null,null,true,false,true,null,true]}, {"operations": ["Trie","search","insert","search"], "args": [[],["a"],["a"],["a"]], "expected": [null,false,null,true]}]',
 ARRAY['trie','blind75'], 'blind75', 'core', '{"trie": true}',
 'Trie', E'class Trie:\n    def __init__(self):\n        pass\n\n    def insert(self, word):\n        pass\n\n    def search(self, word):\n        pass\n\n    def startsWith(self, prefix):\n        pass\n',
 ARRAY['Each trie node needs a dictionary of child nodes keyed by character, plus a flag marking whether a word ends exactly there.', 'search requires that end-of-word flag; startsWith only cares whether the path of characters exists at all.'],
 NULL, 'operations'),

('Design Add and Search Words Data Structure', 'medium', 'trie',
 'Design a data structure that supports adding words and searching for a word, where the search word may contain ''.'' characters that each match any single letter. Implement addWord(word) and search(word). For judging, each testcase is a sequence of operations (the first is the constructor) with their arguments, and the expected return value of each.',
 E'- 1 <= word.length <= 25\n- word consists of lowercase English letters and possibly ''.''  in search calls only.\n- At most 3 * 10^4 total calls.',
 '[{"input": "addWord(\"bad\"); addWord(\"dad\"); addWord(\"mad\"); search(\"pad\"); search(\"bad\"); search(\".ad\"); search(\"b..\")", "output": "[null, null, null, false, true, true, true]", "explanation": "\".ad\" matches \"bad\", \"dad\", or \"mad\"; \"b..\" matches \"bad\"."}]',
 '[{"operations": ["WordDictionary","addWord","addWord","addWord","search","search","search","search"], "args": [[],["bad"],["dad"],["mad"],["pad"],["bad"],[".ad"],["b.."]], "expected": [null,null,null,null,false,true,true,true]}, {"operations": ["WordDictionary","addWord","search","search"], "args": [[],["a"],[".b"],["a"]], "expected": [null,null,false,true]}]',
 ARRAY['trie','backtracking','blind75'], 'blind75', 'core', '{"trie": true}',
 'WordDictionary', E'class WordDictionary:\n    def __init__(self):\n        pass\n\n    def addWord(self, word):\n        pass\n\n    def search(self, word):\n        pass\n',
 ARRAY['A trie works the same way as for plain word storage.', 'When search hits a ''.'', branch into every child at that position instead of just one, since ''.'' can match any letter there.'],
 NULL, 'operations'),

('Find Median from Data Stream', 'hard', 'heap',
 'Design a data structure that supports adding integers one at a time (addNum) and, at any point, returning the median of all numbers added so far (findMedian). For judging, each testcase is a sequence of operations (the first is the constructor) with their arguments, and the expected return value of each (null for the constructor and for addNum).',
 E'- -10^5 <= num <= 10^5\n- findMedian is only called after at least one addNum.\n- At most 5 * 10^4 total calls.',
 '[{"input": "addNum(1); addNum(2); findMedian(); addNum(3); findMedian()", "output": "[null, null, 1.5, null, 2.0]", "explanation": "After [1,2] the median is (1+2)/2 = 1.5; after [1,2,3] the median is the middle value, 2."}]',
 '[{"operations": ["MedianFinder","addNum","addNum","findMedian","addNum","findMedian"], "args": [[],[1],[2],[],[3],[]], "expected": [null,null,null,1.5,null,2.0]}, {"operations": ["MedianFinder","addNum","findMedian"], "args": [[],[5],[]], "expected": [null,null,5.0]}]',
 ARRAY['heap','blind75'], 'blind75', 'core', '{}',
 'MedianFinder', E'class MedianFinder:\n    def __init__(self):\n        pass\n\n    def addNum(self, num):\n        pass\n\n    def findMedian(self):\n        pass\n',
 ARRAY['Keep two heaps: a max-heap for the smaller half of the numbers and a min-heap for the larger half, kept balanced in size.', 'The median is then either the top of whichever heap has one more element, or the average of both tops when they''re equal in size.'],
 NULL, 'operations');
